### ISSUE TITLE
[BUG] AppImage file will open, but closes shortly after.

### ISSUE THREAD

**Issue by MysteryTopHat** [Mocha-Downloader/mocha-downloader#64] opened 2021-12-14 16:13 UTC
I installed the mocha-downloader-0.0.1.AppImage file using AppImageLauncher which can be found here (https://github.com/TheAssassin/AppImageLauncher). I installed it using the Add/Remove software application on Manjaro
There are two options for running this file when you open it, run once, and integrate and run. I will go over what happens when each of those options are chosen.

1. Run Once
Visually, nothing happens. The screen where I had the option to run one or integrate disappears and that's it. However, checking my system processes will show that there are some involving the mocha-downloader running. That's it. 

2. Integrate and Run
This will make the mocha downloader show up in my "all applications" section of the application launcher menu, as it should. The downloader does launch and the icon does pop up on my toolbar for a few seconds, and then disappears. Deleting the appimage and reintegrating it yields the same results.

**Comment by developomp** [comment] 2021-12-14 22:48
A stack trace would be very helpful. Can you run it in the command line?

**Comment by MysteryTopHat** [comment] 2021-12-23 03:31
   ~/Downloads  ./mocha-downloader-0.0.1.AppImage                                                                                                                                                                                  ✔ 
zsh: permission denied: ./mocha-downloader-0.0.1.AppImage
    ~/Downloads  chmod +x ./mocha-downloader-0.0.1.AppImage                                                                                                                                                                     126 ✘ 
    ~/Downloads  ./mocha-downloader-0.0.1.AppImage                                                                                                                                                                                  ✔ 
Extracting usr/share/icons/hicolor/1024x1024/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/1024x1024/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/128x128/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/128x128/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/16x16/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/16x16/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/24x24/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/24x24/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/256x256/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/256x256/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/32x32/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/32x32/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/48x48/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/48x48/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/512x512/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/512x512/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/64x64/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/64x64/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
Extracting usr/share/icons/hicolor/96x96/apps/mocha-downloader.png to "/home/kds0619/.local/share/icons/hicolor/96x96/apps/appimagekit_de0ac36d561c7f5ed537a617cde3f0a7_mocha-downloader.png"
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
gtk-update-icon-cache: Cache file created successfully.
which: no gtk-update-icon-cache-3.0 in (/home/kds0619/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
which: no update-icon-caches in (/home/kds0619/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_mocha-AGTssO/resources/app.asar/node_modules/sharp/lib/sharp.js:30:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/tmp/.mount_mocha-AGTssO/resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
[18882:1222/222854.626760:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.


Also posted in discord, reposted here for my own organization purposes.

**Comment by developomp** [comment] 2021-12-23 03:43
It would be helpful if you surround them with three backticks (the one right above the tab key).

```
It'll make the text look like this
```

**Comment by developomp** [comment] 2021-12-23 03:44
Also, for future people, the problem is related to libvips not being installed in their system. The library will be included in the next release.

**Comment by MysteryTopHat** [comment] 2021-12-23 04:32
> It would be helpful if you surround them with three backticks (the one right above the tab key).
> 
> ```
> It'll make the text look like this
> ```
```Done```

**Closed** 2022-01-02 02:56 UTC
Labels: bug
